[audio]
enable_sounds = true

[bar.default]
center = [ "audio_visualizer", "media", "cat" ]
end = [ "notifications", "bluetooth", "volume", "network", "brightness", "battery", "control-center", "clock", "session" ]
font_weight = 400
margin_edge = 8
margin_ends = 8
padding = 12
radius = 8
thickness = 32
widget_spacing = 12

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

[location]
address = "Kyiv, Ukraine"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 853.0
    cy = 947.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[plugins]
enabled = [ "noctalia/bongocat" ]

[theme]
builtin = "Rosé Pine"
community_palette = "Breeze"
mode = "dark"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "emacs", "foot", "gtk3", "gtk4", "kcolorscheme", "mango", "qt", "starship", "sway" ]
    community_ids = [ "telegram" ]

[wallpaper.default]
path = "/home/miki/Pictures/Wallpapers/dark-souls-3-kiln-of-the-first-flame-uhd-4k-wallpaper.jpg"

[wallpaper.last]
path = "/home/miki/Pictures/Wallpapers/dark-souls-3-kiln-of-the-first-flame-uhd-4k-wallpaper.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/miki/Pictures/Wallpapers/dark-souls-3-kiln-of-the-first-flame-uhd-4k-wallpaper.jpg"

[[wallpaper.favorite]]
builtin_palette = "Rosé Pine"
palette_source = "builtin"
path = "/home/miki/Pictures/Wallpapers/dark-souls-3-kiln-of-the-first-flame-uhd-4k-wallpaper.jpg"
theme_mode = "dark"

[widget.cat]
audio_spectrum = true
tappy_mode = true
type = "noctalia/bongocat:cat"
use_mpris_filter = true

[widget.clock]
format = "{:%Y年%m月%d日 %H:%M}"

[widget.media]
hide_when_no_media = true
max_length = 320

[widget.workspaces]
display = "id"
minimal = true
scale = 1.3500000000000001
names = ["一", "二", "三", "四", "五", "六", "七", "八", "九"]
